### ISSUE TITLE
Main app design

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-ios#3]
Let's use this thread to start to design wireframes and mockups for the main portion of the app: e.g. what they see when they open it, after they've onboarded and logged in.

**Comment by dsernst** [comment]
### Need:

- Sections for `Local`, `State`, `National`
   - each with a list of the current bills to be voted on
- See and update your current representatives
- Link to info pages about Liquid Democracy
- Link to [`Invite friends` feature](https://github.com/Crowdocracy/liquid-ios/issues/2)
- Ability to update your residence

**Comment by dsernst** [comment]
@jaredscheib is this issue where you were thinking of starting?

**Comment by dsernst** [comment]
Quick sketch: 

<img width="361" alt="screen shot 2016-08-21 at 11 18 34 pm" src="https://cloud.githubusercontent.com/assets/6340841/17842912/a9550ba6-67f5-11e6-8aca-53074a957671.png">

**Comment by jaredscheib** [comment]
pushed eslint and react-native skeleton to /react-native

how about a combo of:
https://github.com/aksonov/react-native-tabs on top
https://facebook.github.io/react-native/docs/listview.html for list
https://www.npmjs.com/package/react-native-tab-view on bottom
?

and any experience with:
https://github.com/aksonov/react-native-router-flux
?

**Comment by jaredscheib** [comment]
Nice.

Not just see and update your current representatives, but also set or modify your direct vote. Like I mentioned on #5, where it says "your current position" it could also be a field to set a delegate (or battery of delegates).

How about a deadline for each bill on this page, sorted in descending deadline order? And maybe its sponsor, with a link to find out about that sponsor/author?

It might also be nice, visually/UX-wise, to break up that list view with taller items as well. These could be bills that have a lot of action, bills that need action, bills that you've written/sponsored, or maybe other kinds of interactions that aren't bill-vote related. Just a thought.

A braindump:
As for the page for upcoming elections – it makes me think of this suddenly as a coordination tool for the LDP to focus efforts on winning office. Is this scope creep? Should there be a second app for that, and this app simply be for voting? It also brings up the question of the transitional time before we have a full-on Liquid Democracy in the USA, and thus still actually have representatives that interface with and work within the current system – should we only indicate which bills in the list will actually count due to having an LD candidate? Maybe for legislation where there's not an LD representative, the LD party members' votes can be openly offered and available to non-LD reps as "polling" data?

**Comment by dsernst** [comment]
Good comments. 

I worry this issue isn't focused enough, so I'd like to close it in favor of individual tickets for each of these features.
