### ISSUE TITLE
Voter registration

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-ios#4]
This issue to track the MVP feature for Voter Registration from within the app.

- [x] Input for Full name
- [x] Input for Zip code
- [ ] Input for Residence
- [x] Persist records to db
- [x] Load records from db
- [ ] Validate Zip code

**Comment by dsernst** [comment]
This is just about asking for the same pieces of information as https://join.liquiddemocracy.party , but from right within the app.

**Comment by dsernst** [comment]
Depends upon https://github.com/Crowdocracy/liquid-api/issues/8 for accompanying API endpoint

**Comment by jaredscheib** [comment]
Sounds good. Note that we'll want to treat this in such a way that we can layer in greater identity verification as we implement those features going forward. Not something to worry about for MVP, but important to keep in mind.

In other words, for example, at some point we may have video camera identification, and we would require each person who'd already registered to perform that identity-verification step in order to further layer on security around one person, one identity, truly verified to the same level (or greater) as is optimally required (such as what the current central government requires).

**Comment by dsernst** [comment]
@jaredscheib Good point. We could use this repo's wiki to sketch out ideas for future features like that. I took your suggestion as an example: [wiki: [Possible Verification] Video camera identification](https://github.com/liquidvote/liquid-ios/wiki/%5BPossible-Verification%5D-Video-camera-identification).

**Comment by dsernst** [comment]
Mockup:

<img width="402" alt="screen shot 2016-10-04 at 11 19 02 pm" src="https://cloud.githubusercontent.com/assets/6340841/19103004/01802bac-8a89-11e6-86ce-170197aacb52.png">

**Comment by dsernst** [comment]
The basic front-end logic to implement this mockup was added in https://github.com/liquidvote/liquid-ios/commit/2a25cdba83b50f52517dcad9bbd4e99fc5f0b6fc#diff-bb852d11d34d2d998bd0c146d80acb2aR1

Still need to persist data to and from api.

**Comment by dsernst** [comment]
https://github.com/liquidvote/liquid-ios/commit/1eb953aab95f148ffe172b1b17be6be542a9edeb displays the server's voter registration data

https://github.com/liquidvote/liquid-ios/commit/00d4043bc5d2bc39d56584751259049f4bfc5dc3 persists changes to the server

**Comment by dsernst** [comment]
I'm going to close this for now. 

- Adding a specific field for `Residence address`
- and validating the zip code

can be their own issues when they become important.
